server:
  port: 8082
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: reservation-service
  r2dbc:
    username: root
    password: mysql
    url: r2dbc:mysql://localhost:3306/petclinic_msa
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
